# Generated by Django 4.0.4 on 2022-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0009_tournament_user_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tem_sco',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userg',
            name='userg_email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
