# Generated by Django 4.0.4 on 2022-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0010_team_tem_sco_userg_userg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tourney_nam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tourney_org',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
