# Generated by Django 4.0.4 on 2022-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0012_alter_tournament_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_ended',
            field=models.DateTimeField(null=True),
        ),
    ]
