# Generated by Django 4.0.4 on 2022-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0014_alter_tournament_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_nam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_no_teams',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_sport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_venue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
