# Generated by Django 4.0.4 on 2022-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0015_event_eve_date_event_eve_mode_event_eve_nam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_info',
            field=models.TextField(null=True),
        ),
    ]
