# Generated by Django 4.0.5 on 2022-10-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0016_event_eve_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tem_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
